### ISSUE TITLE
Provision

### ISSUE THREAD

**Issue by teddybee-r** [PabloSzx/Gwent-Cards#2]
Please replace something to display Provisions.

If you need new images you can send them to me (or a script that pulls them from the json source) I can host them on https://gwent.seven7y.com/

I'm writing here because the discord tag you mentioned is dead (PabloSz#0327).

**Comment by PabloSzx** [comment]
I'm sorry, i have not been playing gwent lately, could you explain what Provisions are? ([my data source](https://github.com/GwentCommunityDevelopers/gwent-data-release)) doesn't have anything about provisions.

**Comment by teddybee-r** [comment]
The provision is the core of the new deck building.

4x Gold, 6x Silver, 3x Bronze copy limit has been replaced with provisions

New deckbuilding rules:
1x Gold copy
2x Bronze copies
Maximum deck cards: 25
Maximum provision: 165

the bot displays "Lane: Any" this should be replaced with "Provision: #"


the data source has provisions!

my card database build with the same data source:
https://gwent.seven7y.com/hc.php?lang=en

Leader cards have the amount of redraws displayed on them (they have no strength)
https://gwent.seven7y.com/hc-card.php?card=202148&lang=en

example card
https://gwent.seven7y.com/hc-card.php?card=132215&lang=en
provision cost is displayed on the bottom right

**Comment by PabloSzx** [comment]
I am fixing it right now, but i don't have the translation for provision on different languages, do you that data available?.
Edit: it is working right now, provision data implemented

**Comment by PabloSzx** [comment]
And about the images, i would need a complete image, [the image](https://img.seven7y.com/g/c/h/132215.png) you have hosted on your website only has the character behind the card, not the card itself.
If you can provide it, and the route just needs the variation number, i could put your website logo below the card and the redirection to your page.

**Comment by teddybee-r** [comment]
I've pulled the images from the json source
https://img.seven7y.com/g/cardbot/low/#id#.png
https://img.seven7y.com/g/cardbot/thumb/#id#.png

Total images pulled: 435
Missing: 56
Image [status is known](https://github.com/GwentCommunityDevelopers/gwent-data-release/issues/14)

You can remove the website logo. if you want to link to cards you can do that.

I support &lang= en,pl,ru,de,fr,es,it,jp,pt,cn,kr
Korean is currently not in the menu but other than that it is fully supported in the card database.

**Comment by PabloSzx** [comment]
If you could hand me the translations for "Provision" for all those languages it would be very helpful.
I am using your website now for the images, and i'm using the link format i thought i could use, https://gwent.seven7y.com/hc-card.php?card=#id#.
![deepinscreenshot_select-area_20181101235744](https://user-images.githubusercontent.com/8672915/47891463-1cefaa80-de32-11e8-9b69-60f2fb3d4895.png)

**Comment by teddybee-r** [comment]
I wrote a message to cdpr if they can help providing a translation of provision. I'll let you know if they can help out.

**Comment by PabloSzx** [comment]
I will close the issue for now, if i ever get the pending translation i will add it to the bot.
